### ISSUE TITLE
Allow service observers to bind to model in tag

### ISSUE THREAD

**Issue by wouterj** [wouterj/WouterJEloquentBundle#52]
E.g.
```yml
app.user_observer:
    class: AppBundle\Observer\UserObserver
    tags:
        - { name: wouterj_eloquent.observer, model: AppBundle\Model\User }
```

This requires some more work, as it needs to bind on each request instead of just once during container building. This might require adding a new initializers.
